### ISSUE TITLE
Multiple SVGs Coordinates

### ISSUE THREAD

**Issue by jsmrcaga** [hueitan/snap.svg.zpd#49]
I have come accross a very specific issue. I have a website where I have 3 different SVGs (meaning 3 different DOM elements), one under each other. 
When I activate `pan` and `zoom` it seems to be working fine. But deactivating `zoom` (only `pan` set to true) seems to move the origin points of the two svgs that were off-centered when the page loaded. I have seen this behaviour on IE and Firefox, it works fine on Chrome.

I explain: when you first load the page, SVG number 1 is the "most-centered" on the view port. This svg will have normal center coordinates. However the two others won't. I made two buttons for zooming in and out. Zooming on the first one zooms to it's center, but zooming on the two others will misplace them to the bottom (sometimes even getting them out of view)
The same way, if you scroll to center the 2nd one and refresh, same problem happens, but this time the 2nd SVG will zoom normally.

**Comment by tikiatua** [comment]
Hi @jsmrcaga,

this problem is probably due to the fact, that snap.svg.zpd was originally intended to be used for one single element on a page only.

Due to the current implementation of the plugin the internal "data-store" is re-used for all svg-elements handled by snap.svg.zpd. This is actually incorrect will lead to the problems you described.

The beta-version (separate branch) is implemented with a completely different internal structure and should solve your problems. Please be aware that the beta-version does not implement all functionality of the master branch yet and will probably require some code tweaking to make it work for you. 

Nonetheless, we have been using it successfully in production for several weeks now without any problems.

**Comment by hueitan** [comment]
So ideally the `snap.svg.zpd` should handle multiple elements on a page, and there are all independent.
